[flags]
rate = 1000

[styles.cpu]
all_entry_colour  = "#c300ff"
avg_entry_colour  = "#00e5ff"
cpu_core_colours  = [
    "#c300ff",
    "#00e5ff",
    "#00ff87",
    "#f0e130",
    "#ff6e00",
    "#ff2079",
    "#39a0ed",
    "#a8ff78",
]

[styles.memory]
ram_colour  = "#00ff87"
swap_colour = "#f0e130"

[styles.network]
rx_colour = "#00e5ff"
tx_colour = "#ff2079"

[styles.battery]
high_battery_colour   = "#00ff87"
medium_battery_colour = "#f0e130"
low_battery_colour    = "#ff2079"

[styles.widgets]
border_colour          = "#2d0042"
selected_border_colour = "#c300ff"
widget_title           = { colour = "#c5c8c6" }
text                   = { colour = "#c5c8c6" }
selected_text          = { colour = "#000000", bg_colour = "#c300ff" }

[styles.tables]
headers = { colour = "#c300ff", bold = true }

[styles.graphs]
graph_colour = "#2d0042"
legend_text  = { colour = "#c5c8c6" }
