[colors]
transparent_background_colors = true

[colors.cursor]
cursor = "#ff9900"

[colors.vi_mode_cursor]
cursor = "#aa00ff"

[colors.primary]
background = "#000000"
foreground = "#c5c8c6"

[colors.normal]
black   = "#1d1f21"
red     = "#db0226"
green   = "#12a802"
yellow  = "#ffea00"
blue    = "#0073ff"
magenta = "#ee00ff"
cyan    = "#00fbff"
white   = "#c5c8c6"

[cursor]
style            = "Beam"
unfocused_hollow = true

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
bold   = { family = "SauceCodePro Nerd Font", style = "Bold" }
italic = { family = "SauceCodePro Nerd Font", style = "Italic" }
size   = 12.0

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Control|Shift"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
opacity       = 0.6
dynamic_title = true

[window.padding]
x = 10
y = 10
